pipeline {
  agent none
  stages {
    stage('Back-end - Java Hello World') {
      agent {
        docker { image 'openjdk:11-jdk-slim' }
      }
      steps {
        // Compile and run a Java Hello World application
        sh '''
        echo "public class HelloWorld { public static void main(String[] args) { System.out.println(\\"Hello, World from Java!\\"); }}" > HelloWorld.java
        javac HelloWorld.java
        java HelloWorld
        '''
      }
    }
    stage('Front-end - Python Application') {
      agent {
        docker { image 'python:3.10-alpine' }
      }
      steps {
        // Run a simple Python script
        sh '''
        echo "print('Hello, World from Python!')" > hello.py
        python hello.py
        '''
      }
    }
  }
}
